//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using CapaModelo;
    using System.Web.Mvc;
    using System.Web.Mvc.Html;
    
    
    public class Index : System.Web.Mvc.WebViewPage<List<CapaPresentacion.Models.OrdenValidacionFinancieraVM>> {
        
#line hidden
        
        public Index() {
        }
        
        public override void Execute() {
WriteLiteral("\r\n");

  
    ViewBag.Title = "Dashboard Financiero";

WriteLiteral(@"

<style>
    .acciones-cell {
        min-width: 150px;
    }

    .acciones-orden {
        display: flex;
        align-items: center;
        gap: .35rem;
        flex-wrap: wrap;
    }

    .acciones-orden form {
        margin: 0;
    }

    .btn-accion {
        width: 32px;
        height: 32px;
        padding: 0;
        border-radius: 8px;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        line-height: 1;
    }

    .btn-pdf {
        width: 30px;
        height: 30px;
        padding: 0;
        border-radius: 8px;
        display: inline-flex;
        align-items: center;
        justify-content: center;
    }
</style>

<h2>Financiero – Validación de Órdenes</h2>
<hr />

");

 if (TempData["Success"] != null)
{

WriteLiteral("    <div");

WriteLiteral(" class=\"alert alert-success\"");

WriteLiteral(">");

                                Write(TempData["Success"]);

WriteLiteral("</div>\r\n");

}

 if (TempData["Error"] != null)
{

WriteLiteral("    <div");

WriteLiteral(" class=\"alert alert-danger\"");

WriteLiteral(">");

                               Write(TempData["Error"]);

WriteLiteral("</div>\r\n");

}

 if (ViewBag.SinResultadosConFiltro == true)
{

WriteLiteral("    <div");

WriteLiteral(" class=\"alert alert-warning\"");

WriteLiteral(">\r\n        No se encontraron órdenes con el estado seleccionado. Se muestran toda" +
"s las órdenes disponibles (Total: ");

                                                                                                           Write(ViewBag.TotalSinFiltro);

WriteLiteral(").\r\n    </div>\r\n");

}

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"d-flex justify-content-end mb-3\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" method=\"get\"");

WriteLiteral(" class=\"d-flex align-items-center gap-2\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"mb-0 text-muted\"");

WriteLiteral(">Estado:</label>\r\n        <select");

WriteLiteral(" name=\"estado\"");

WriteLiteral(" class=\"form-select form-select-sm\"");

WriteLiteral(" onchange=\"this.form.submit()\"");

WriteLiteral(">\r\n<option");

WriteLiteral(" value=\"PROCESADA\"");

WriteLiteral(" ");

                      Write(ViewBag.EstadoFiltro == "PROCESADA" ? "selected" : "");

WriteLiteral(">En revisión</option>\r\n<option");

WriteLiteral(" value=\"PENDIENTE\"");

WriteLiteral(" ");

                      Write(ViewBag.EstadoFiltro == "PENDIENTE" ? "selected" : "");

WriteLiteral(">Pendiente</option>\r\n<option");

WriteLiteral(" value=\"FACTURADA\"");

WriteLiteral(" ");

                      Write(ViewBag.EstadoFiltro == "FACTURADA" ? "selected" : "");

WriteLiteral(">Facturada</option>\r\n<option");

WriteLiteral(" value=\"COMPLETADA\"");

WriteLiteral(" ");

                       Write(ViewBag.EstadoFiltro == "COMPLETADA" ? "selected" : "");

WriteLiteral(">Completada</option>\r\n<option");

WriteLiteral(" value=\"ANULADA\"");

WriteLiteral(" ");

                    Write(ViewBag.EstadoFiltro == "ANULADA" ? "selected" : "");

WriteLiteral(">Anulada</option>\r\n<option");

WriteLiteral(" value=\"TODAS\"");

WriteLiteral(" ");

                  Write(ViewBag.EstadoFiltro == "TODAS" ? "selected" : "");

WriteLiteral(">Todas</option>\r\n        </select>\r\n    </form>\r\n</div>\r\n\r\n<table");

WriteLiteral(" class=\"table table-striped\"");

WriteLiteral(@">
    <thead>
        <tr>
            <th>#</th>
            <th>Orden</th>
            <th>Compañía</th>
            <th>Fecha</th>
            <th>Monto</th>
            <th>Estado</th>
            <th>Comprobante</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
");

        
         if (Model != null && Model.Any())
        {
            int i = 1;
            foreach (var item in Model)
            {
                var orden = item.Orden;
                var pago = item.Pago;
                var estadoNorm = orden != null ? ((orden.Estado ?? "").Trim().ToUpperInvariant().Replace(" ", "_")) : "";
                var puedeGestionarPago = pago != null && (estadoNorm == "PROCESADA" || estadoNorm == "PENDIENTE");

WriteLiteral("        <tr>\n            <td>");

           Write(Html.Encode(i));

WriteLiteral("</td>\r\n            <td>");

           Write(Html.Encode(orden != null ? orden.NumeroOrden : "-"));

WriteLiteral("</td>\r\n            <td>");

           Write(Html.Encode(orden != null ? (orden.NombreContribuyente ?? orden.Compania) : "-"));

WriteLiteral("</td>\r\n            <td>");

           Write(Html.Encode(orden != null ? orden.FechaCreacion.ToString("dd/MM/yyyy") : ""));

WriteLiteral("</td>\r\n            <td>");

           Write(Html.Encode(orden != null ? orden.Total.ToString("N2") : "0.00"));

WriteLiteral("</td>\r\n            <td>");

           Write(Html.Encode(orden != null ? orden.Estado : ""));

WriteLiteral("</td>\r\n            <td>\n");

                
                 if (orden != null)
                {

WriteLiteral("                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3695), Tuple.Create("\"", 3772)
, Tuple.Create(Tuple.Create("", 3702), Tuple.Create<System.Object, System.Int32>(Url.Action("DescargarPdf", "OrdenRecaudacion", new { id = orden.Id })
, 3702), false)
);

WriteLiteral("\n                       target=\"_blank\"");

WriteLiteral("\n                       class=\"btn btn-outline-secondary btn-sm btn-pdf\"");

WriteLiteral("\n                       title=\"Ver PDF de la orden\"");

WriteLiteral(">\n                        <i");

WriteLiteral(" class=\"fas fa-file-pdf\"");

WriteLiteral("></i>\n                    </a>\n");

                }
                else
                {

WriteLiteral("                    <span");

WriteLiteral(" class=\"text-muted\"");

WriteLiteral(">Sin orden</span>\n");

                }

WriteLiteral("            </td>\n            <td");

WriteLiteral(" class=\"acciones-cell\"");

WriteLiteral(">\n");

                
                 if (orden != null)
                {

WriteLiteral("                    <div");

WriteLiteral(" class=\"acciones-orden\"");

WriteLiteral(">\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4341), Tuple.Create("\"", 4414)
, Tuple.Create(Tuple.Create("", 4348), Tuple.Create<System.Object, System.Int32>(Url.Action("Detalles", "OrdenRecaudacion", new { id = orden.Id })
, 4348), false)
);

WriteLiteral("\n                           class=\"btn btn-outline-primary btn-sm btn-accion\"");

WriteLiteral("\n                           title=\"Ver detalles\"");

WriteLiteral(">\n                            <i");

WriteLiteral(" class=\"fas fa-eye\"");

WriteLiteral("></i>\n                        </a>\n\n");

                        
                         if (puedeGestionarPago)
                        {

WriteLiteral("                            <form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create("\n                                  action=\"", 4749), Tuple.Create("\"", 4832)
, Tuple.Create(Tuple.Create("", 4792), Tuple.Create<System.Object, System.Int32>(Url.Action("AprobarPago", "Financiero")
, 4792), false)
);

WriteLiteral("\n                                  class=\"d-inline m-0\"");

WriteLiteral(">\n");

WriteLiteral("                                ");

                           Write(Html.AntiForgeryToken());

WriteLiteral("\n                                <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"id\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5009), Tuple.Create("\"", 5026)
, Tuple.Create(Tuple.Create("", 5017), Tuple.Create<System.Object, System.Int32>(orden.Id
, 5017), false)
);

WriteLiteral(" />\n                                <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"pagoId\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5097), Tuple.Create("\"", 5121)
, Tuple.Create(Tuple.Create("", 5105), Tuple.Create<System.Object, System.Int32>(pago.CodigoPago
, 5105), false)
);

WriteLiteral(" />\n                                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-success btn-sm btn-accion\"");

WriteLiteral(" title=\"Aprobar pago\"");

WriteLiteral(">\n                                    <i");

WriteLiteral(" class=\"fas fa-check\"");

WriteLiteral("></i>\n                                </button>\n                            </for" +
"m>\n");



WriteLiteral("                            <button");

WriteLiteral(" class=\"btn btn-danger btn-sm btn-accion\"");

WriteLiteral(" type=\"button\"");

WriteLiteral("\n                                    title=\"Rechazar\"");

WriteLiteral("\n                                    data-bs-toggle=\"modal\"");

WriteLiteral(" data-bs-target=\"#modalRechazo-");

                                                                                    Write(orden.Id);

WriteLiteral("\"");

WriteLiteral(">\n                                <i");

WriteLiteral(" class=\"fas fa-times\"");

WriteLiteral("></i>\n                            </button>\n");

WriteLiteral("                            <div");

WriteLiteral(" class=\"modal fade\"");

WriteAttribute("id", Tuple.Create(" id=\"", 5783), Tuple.Create("\"", 5810)
, Tuple.Create(Tuple.Create("", 5788), Tuple.Create("modalRechazo-", 5788), true)
, Tuple.Create(Tuple.Create("", 5801), Tuple.Create<System.Object, System.Int32>(orden.Id
, 5801), false)
);

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\n                                <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\n                                    <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\n                                        <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\n                                            <h5");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">Rechazar Orden</h5>\n                                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-close\"");

WriteLiteral(" data-bs-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral("></button>\n                                        </div>\n                       " +
"                 <form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 6367), Tuple.Create("\"", 6418)
, Tuple.Create(Tuple.Create("", 6376), Tuple.Create<System.Object, System.Int32>(Url.Action("RechazarOrden", "Financiero")
, 6376), false)
);

WriteLiteral(">\n");

WriteLiteral("                                            ");

                                       Write(Html.AntiForgeryToken());

WriteLiteral("\n                                            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"id\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6564), Tuple.Create("\"", 6581)
  , Tuple.Create(Tuple.Create("", 6572), Tuple.Create<System.Object, System.Int32>(orden.Id
, 6572), false)
);

WriteLiteral(" />\n                                            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\n                                                <label");

WriteLiteral(" class=\"form-label\"");

WriteLiteral(">Motivo</label>\n                                                <textarea");

WriteLiteral(" name=\"motivo\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" rows=\"3\"");

WriteLiteral(" required></textarea>\n                                            </div>\n        " +
"                                    <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\n                                                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-secondary\"");

WriteLiteral(" data-bs-dismiss=\"modal\"");

WriteLiteral(">Cancelar</button>\n                                                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-danger\"");

WriteLiteral(">Rechazar</button>\n                                            </div>\n           " +
"                             </form>\n                                    </div>\n" +
"                                </div>\n                            </div>\n");

                        }

WriteLiteral("                    </div>\n");

                    }

WriteLiteral("                }\n            </td>\n        </tr>\n");

                i++;
            }
        }
        else
        {

WriteLiteral("            <tr>\r\n                <td");

WriteLiteral(" colspan=\"8\"");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                    No hay registros para el estado seleccionado.\r\n           " +
"     </td>\r\n            </tr>\r\n");

        }

WriteLiteral("    </tbody>\r\n</table>\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n");

        }
    }
}

