using System;
using System.IO;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using CapaModelo.Common;
using CapaNegocio.Services;

namespace AOCR.Tests.Unit
{
    [TestClass]
    public class GateHDcavFlowTests
    {
        [TestMethod]public void EstadoCentralDirdac_EstaDefinido(){StringAssert.Contains(Read("CapaDatos/Constants/AocrEstadosProceso.cs"),"PENDIENTE_REVISION_INFORME_DIRDAC");}
        [TestMethod]public void BandejaDirdac_UsaEstadoCentral_NoConsultaLegacy(){var dao=Read("CapaDatos/DAOs/InspeccionInformeDAO.cs");var start=dao.IndexOf("ListarPendientesRevisionInformeDirdac",StringComparison.Ordinal);var body=dao.Substring(start,Math.Min(900,dao.Length-start));StringAssert.Contains(body,"PendienteRevisionInformeDirdac");Assert.IsFalse(body.Contains("ListarPendientesFirmaDirdac"));}
        [TestMethod]public void BandejaDirdac_RecuperaSoloFirmasInspectorValidasSinTransicionCentral(){var dao=Read("CapaDatos/DAOs/InspeccionInformeDAO.cs");var start=dao.IndexOf("ListarInspeccionesFirmadasSinTransicionDcav",StringComparison.Ordinal);var body=dao.Substring(start,Math.Min(3200,dao.Length-start));StringAssert.Contains(body,"FIRMADO_INSPECTOR");StringAssert.Contains(body,"PENDIENTE_REVISION_INFORME_DIRDAC");StringAssert.Contains(body,"SATISFACTORIO");StringAssert.Contains(body,"ruta_documento_firmado");}
        [TestMethod]public void TransicionInspector_AsignaResponsableDirdac(){var c=Read("CapaPresentacion/Controllers/InspeccionController.cs");StringAssert.Contains(c,"AocrEstadosProceso.PendienteRevisionInformeDirdac");StringAssert.Contains(c,"ROL_DIRDAC");StringAssert.Contains(c,"SATISFACTORIO");}
        [TestMethod]public void AprobacionDirdac_HabilitaAmbosDocumentosAlInspector(){var c=Read("CapaPresentacion/Controllers/InspeccionController.cs");StringAssert.Contains(c,"AocrEstadosProceso.InformeTecnicoAprobadoDirdac");StringAssert.Contains(c,"AocrEstadosProceso.DocumentosFinalesPorGenerar");StringAssert.Contains(c,"SincronizarSolicitudAocrTrasFirmaFinal");}
        [TestMethod]public void DirectorDcav_PuedeEntrarYFirmarCondiciones(){var roles=Read("CapaDatos/Constants/AocrRolesInstitucionales.cs");StringAssert.Contains(roles,"DirectorCertificacionesDcav");StringAssert.Contains(Read("CapaPresentacion/Services/FirmaAocrServices.cs"),"AocrRolesInstitucionales.DcavAliases");var c=Read("CapaPresentacion/Controllers/CoordinacionJefaturaController.cs");var i=c.IndexOf("public ActionResult FirmarCondiciones",StringComparison.Ordinal);StringAssert.Contains(c.Substring(Math.Max(0,i-500),Math.Min(900,c.Length-Math.Max(0,i-500))),"DirectorCertificacionesDcav");}
        [TestMethod]public void MigracionIncluyeRollback(){Assert.IsTrue(File.Exists(Path.Combine(Root(),"scripts/sql/012_gate_h_dcav_estado_central.sql")));Assert.IsTrue(File.Exists(Path.Combine(Root(),"scripts/sql/012_gate_h_dcav_estado_central_rollback.sql")));}
        [TestMethod]public void CierreExigeDosFirmasHashTamanoFirmanteYArchivo(){var s=Read("CapaNegocio/Services/AocrFinalizacionService.cs");StringAssert.Contains(s,"DocumentoFirmadoValido");StringAssert.Contains(s,"HashDocumento");StringAssert.Contains(s,"TamanioPdfFirmado");StringAssert.Contains(s,"FirmadoPorRol");StringAssert.Contains(s,"rutaExiste(firma.RutaDocumento)");}
        [TestMethod]public void CierreEsBloqueadoPorNoConformidadesVigentes(){var s=Read("CapaNegocio/Services/AocrFinalizacionService.cs");StringAssert.Contains(s,"ListarPorSolicitud");StringAssert.Contains(s,"NcBloqueaCierre");StringAssert.Contains(s,"no conformidades pendientes");}
        [TestMethod]public void NotificacionFinalVerificaSha256YDestinatarioDcav(){var s=Read("CapaNegocio/Services/AocrProcesoNotificacionService.cs");StringAssert.Contains(s,"SHA256.Create");StringAssert.Contains(s,"hash no coincide");StringAssert.Contains(s,"DirectorCertificacionesDcav");StringAssert.Contains(s,"SKIP_DUPLICADO");}
        [TestMethod]public void DescargarCondiciones_NoFinalizaComoEfectoSecundario(){var c=Read("CapaPresentacion/Controllers/SolicitudAOCRController.cs");var i=c.IndexOf("DescargarCondicionesLimitacionesModificacion",StringComparison.Ordinal);var body=c.Substring(i,Math.Min(4200,c.Length-i));Assert.IsFalse(body.Contains("Descarga final de Condiciones y Limitaciones firmada por RT"));}
        [TestMethod]public void FirmaActualizaEstadoCentralDeModulosSieteYOcho(){var c=Read("CapaPresentacion/Controllers/FirmaAocrController.cs");var dao=Read("CapaDatos/DAOs/DocumentosFinalesWorkflowDAO.cs");StringAssert.Contains(c,"RegistrarFirmaInstitucional");StringAssert.Contains(dao,"AocrEstadosProceso.AocrFirmadoDirdac");StringAssert.Contains(dao,"AocrEstadosProceso.CondicionesFirmadasDcav");StringAssert.Contains(dao,"AocrEstadosProceso.Finalizado");Assert.IsFalse(c.Contains("ActualizarEstadoCentralSeguro"));}
        [TestMethod]public void CierreGateH_TieneMigracionIdempotenteYRollback(){var sql=Read("scripts/sql/013_gate_h_cierre_modulos_7_8.sql");StringAssert.Contains(sql,"CREATE UNIQUE INDEX IF NOT EXISTS");Assert.IsTrue(File.Exists(Path.Combine(Root(),"scripts/sql/013_gate_h_cierre_modulos_7_8_rollback.sql")));}
        [TestMethod]public void EstadoCentral_ReintentoEsIdempotenteYSinTransaccionNpgsqlAnidada(){var dao=Read("CapaDatos/DAOs/AocrProcesoEstadoDAO.cs");StringAssert.Contains(dao,"pg_advisory_xact_lock");StringAssert.Contains(dao,"NOT EXISTS(SELECT 1 FROM mismo)");Assert.IsFalse(dao.Contains("cn.BeginTransaction()"),"El DAO debe participar del TransactionScope institucional, no abrir una transacción Npgsql anidada.");}
        [TestMethod]public void ReparacionDcav_ReemplazaEstadoActivoAnteriorYTieneRollbackSeguro(){var sql=Read("scripts/sql/20260718_reparar_bandeja_revision_dcav.sql");StringAssert.Contains(sql,"estado_actual<>'PENDIENTE_REVISION_INFORME_DCAV'");StringAssert.Contains(sql,"SET activo=FALSE");StringAssert.Contains(sql,"REPARACION_20260718");Assert.IsTrue(File.Exists(Path.Combine(Root(),"scripts/sql/20260718_reparar_bandeja_revision_dcav_rollback.sql")));}
        [TestMethod]public void FirmaInspector_NoSeConfundeConEnvioADireccion(){Assert.IsFalse(InformeTecnicoEstadosInstitucionales.FueEnviadoDireccion("FIRMADO_INSPECTOR"));Assert.IsFalse(InformeTecnicoEstadosInstitucionales.FueEnviadoDireccion("FIRMADO_POR_INSPECTOR"));Assert.IsTrue(InformeTecnicoEstadosInstitucionales.FueEnviadoDireccion("ENVIADO_A_DIRDAC"));}
        [TestMethod]public void ReparacionDcav_IncluyeInformesFirmadosQueQuedaronSinEstadoCentral(){var sql=Read("scripts/sql/20260718_reparar_bandeja_revision_dcav.sql");StringAssert.Contains(sql,"'FIRMADO_INSPECTOR'");StringAssert.Contains(sql,"'INFORME_TECNICO_FIRMADO_INSPECTOR'");}
        [TestMethod]public void ContadorDireccion_UsaLaMismaConsultaQueLaBandeja(){var service=Read("CapaNegocio/Services/DireccionBandejaService.cs");var start=service.IndexOf("ContarFirmasPendientesDirdac",StringComparison.Ordinal);var body=service.Substring(start,Math.Min(500,service.Length-start));StringAssert.Contains(body,"ContarPendientesRevisionDirdac()");Assert.IsFalse(body.Contains("ListarPendientesFirmaDirdac"));}
        [TestMethod]public void FirmaInstitucional_ActualizaEstadoCentralEnLaTransaccionAutoritativa(){var c=Read("CapaPresentacion/Controllers/FirmaAocrController.cs");var s=Read("CapaDatos/DAOs/DocumentosFinalesWorkflowDAO.cs");StringAssert.Contains(c,"RegistrarFirmaInstitucional");StringAssert.Contains(s,"CambiarEstadoExpediente");StringAssert.Contains(s,"AocrEstadosProceso.Finalizado");}
        [TestMethod]public void BandejasFirma_SeparanAocrYCondiciones(){var fila=new AocrBandejaDocumentoRow{TipoSolicitud=1,EstadoSolicitudRaw="AOCR_EN_ELABORACION"};Assert.IsTrue(AocrFirmaPendientePolicy.EsAocrPendienteFirma(fila));Assert.IsTrue(AocrFirmaPendientePolicy.EsCondicionesPendienteFirma(fila));fila.FirmaReconocimientoId=10;Assert.IsFalse(AocrFirmaPendientePolicy.EsAocrPendienteFirma(fila));Assert.IsTrue(AocrFirmaPendientePolicy.EsCondicionesPendienteFirma(fila));fila.FirmaCondicionesId=11;Assert.IsFalse(AocrFirmaPendientePolicy.EsCondicionesPendienteFirma(fila));}
        [TestMethod]public void SidebarFirma_NoEnviaAocrNiCondicionesALaBandejaDeInformes(){var sidebar=Read("CapaPresentacion/Helpers/SidebarMenuBuilder.cs");var aocr=sidebar.IndexOf("firm-dir-aocr",StringComparison.Ordinal);var body=sidebar.Substring(aocr,Math.Min(700,sidebar.Length-aocr));StringAssert.Contains(body,"SolicitudAOCR");StringAssert.Contains(body,"DocumentoAocr");Assert.IsFalse(body.Contains("\"Inspeccion\", \"PendientesDireccion\""));}
        [TestMethod]public void SidebarDirdac_UsaMatrizExclusivaEnLugarDelMenuGenerico(){var sidebar=Read("CapaPresentacion/Helpers/SidebarMenuBuilder.cs");StringAssert.Contains(sidebar,"var navegacionPorRol = context.TieneNavegacionRol && !context.EsAdministrador");StringAssert.Contains(sidebar,"BuildRoleWorkMenuGroup(context)");StringAssert.Contains(sidebar,"dirdac-revision-informes");StringAssert.Contains(sidebar,"dirdac-aocr-pendientes");StringAssert.Contains(sidebar,"dirdac-aocr-firmados");}
        [TestMethod]public void SidebarDirdac_NoMuestraContextoCompaniaIrrelevante(){var view=Read("CapaPresentacion/Views/Shared/_Sidebar.cshtml");var model=Read("CapaPresentacion/Models/ViewModels/SidebarMenuContextViewModel.cs");StringAssert.Contains(view,"sidebar.ShowCompanyContext");StringAssert.Contains(model,"ShowCompanyContext");}
        [TestMethod]public void DashboardDirdac_ExponeTresTareasPrincipalesYAutorizaAliasInstitucionales(){var view=Read("CapaPresentacion/Views/Direccion/DashboardGerencial.cshtml");var controller=Read("CapaPresentacion/Controllers/5_DireccionController.cs");StringAssert.Contains(view,"Centro de decisiones DIRDAC");StringAssert.Contains(view,"Informes por revisar");StringAssert.Contains(view,"AOCR pendientes de firma");StringAssert.Contains(view,"Documentos firmados");StringAssert.Contains(controller,"DireccionJefaturaTecnica,JefaturaTecnica,DIRDAC,DirectorGeneral");}
        [TestMethod]public void BandejaDirdac_TieneBusquedaMetricasYAccesoDirectoAFirmaAocr(){var view=Read("CapaPresentacion/Views/InformeTecnico/PendientesDireccion.cshtml");StringAssert.Contains(view,"dirdacTraySearch");StringAssert.Contains(view,"Pendientes de decisión");StringAssert.Contains(view,"PDF firmado disponible");StringAssert.Contains(view,"DocumentoPendiente = \"AOCR\"");}
        [TestMethod]public void DashboardCoordinacion_NoExponeAccionesDirdacPorRolesInactivos(){var controller=Read("CapaPresentacion/Controllers/CoordinacionJefaturaController.cs");var view=Read("CapaPresentacion/Views/CoordinacionJefatura/DashboardInspeccion.cshtml");StringAssert.Contains(controller,"SidebarPermissionHelper.Resolve");StringAssert.Contains(controller,"PuedeVerPendientesDirdacRolActivo");StringAssert.Contains(view,"ViewBag.PuedeVerPendientesDirdacRolActivo");StringAssert.Contains(view,"GeneradasFirmadas");}
        private static string Read(string path){return File.ReadAllText(Path.Combine(Root(),path.Replace('/',Path.DirectorySeparatorChar)));}
        private static string Root(){return Path.GetFullPath(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"..","..",".."));}
    }
}
