-- =============================================================
-- AOCR - Migracion financiera: factura de pago + adjuntos de email
-- Motor: DB2
-- Fecha: 2026-02-20
-- NOTA: Ejecutar en el esquema AOCR correspondiente.
-- =============================================================
--#SET TERMINATOR @

BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM SYSCAT.TABLES
        WHERE TABSCHEMA = CURRENT SCHEMA
          AND TABNAME = 'AOCR_TB_FACTURA_PAGO'
    ) THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE AOCR_TB_FACTURA_PAGO (
                ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                ORDEN_ID INTEGER NOT NULL,
                PAGO_ID INTEGER,
                NUMERO_FACTURA VARCHAR(80) NOT NULL,
                AUTORIZACION_FACTURA VARCHAR(80),
                FECHA_EMISION DATE NOT NULL,
                SUBTOTAL DECIMAL(18,2) NOT NULL,
                IVA DECIMAL(18,2) NOT NULL,
                TOTAL DECIMAL(18,2) NOT NULL,
                OBSERVACIONES CLOB(1M),
                FILE_NAME VARCHAR(255) NOT NULL,
                CONTENT_TYPE VARCHAR(120) NOT NULL,
                FILE_SIZE BIGINT NOT NULL,
                FILE_PATH CLOB(2M) NOT NULL,
                CREADO_POR VARCHAR(120),
                CREADO_EN TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP
            )';
    END IF;
END@

BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM SYSCAT.INDEXES
        WHERE TABSCHEMA = CURRENT SCHEMA
          AND INDNAME = 'UQ_FACTURA_PAGO_ORDEN'
    ) THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UQ_FACTURA_PAGO_ORDEN ON AOCR_TB_FACTURA_PAGO (ORDEN_ID)';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM SYSCAT.INDEXES
        WHERE TABSCHEMA = CURRENT SCHEMA
          AND INDNAME = 'UQ_FACTURA_PAGO_PAGO'
    ) THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UQ_FACTURA_PAGO_PAGO ON AOCR_TB_FACTURA_PAGO (PAGO_ID)';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM SYSCAT.INDEXES
        WHERE TABSCHEMA = CURRENT SCHEMA
          AND INDNAME = 'IX_FACTURA_PAGO_FECHA'
    ) THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IX_FACTURA_PAGO_FECHA ON AOCR_TB_FACTURA_PAGO (FECHA_EMISION)';
    END IF;
END@

BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM SYSCAT.COLUMNS
        WHERE TABSCHEMA = CURRENT SCHEMA
          AND TABNAME = 'EMAIL_QUEUE'
          AND COLNAME = 'EVENT_KEY'
    ) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMAIL_QUEUE ADD COLUMN EVENT_KEY VARCHAR(200)';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM SYSCAT.COLUMNS
        WHERE TABSCHEMA = CURRENT SCHEMA
          AND TABNAME = 'EMAIL_QUEUE'
          AND COLNAME = 'ERROR_MESSAGE'
    ) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMAIL_QUEUE ADD COLUMN ERROR_MESSAGE CLOB(64K)';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM SYSCAT.COLUMNS
        WHERE TABSCHEMA = CURRENT SCHEMA
          AND TABNAME = 'EMAIL_QUEUE'
          AND COLNAME = 'INTENTOS'
    ) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMAIL_QUEUE ADD COLUMN INTENTOS INTEGER NOT NULL DEFAULT 0';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM SYSCAT.COLUMNS
        WHERE TABSCHEMA = CURRENT SCHEMA
          AND TABNAME = 'EMAIL_QUEUE'
          AND COLNAME = 'UPDATED_AT'
    ) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EMAIL_QUEUE ADD COLUMN UPDATED_AT TIMESTAMP';
    END IF;
END@

BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM SYSCAT.INDEXES
        WHERE TABSCHEMA = CURRENT SCHEMA
          AND INDNAME = 'UX_EMAIL_QUEUE_EVENT_KEY'
    ) THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_EMAIL_QUEUE_EVENT_KEY ON EMAIL_QUEUE (EVENT_KEY)';
    END IF;
END@

BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM SYSCAT.TABLES
        WHERE TABSCHEMA = CURRENT SCHEMA
          AND TABNAME = 'EMAIL_ATTACHMENT'
    ) THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE EMAIL_ATTACHMENT (
                ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                EMAIL_QUEUE_ID INTEGER NOT NULL,
                FILE_NAME VARCHAR(255) NOT NULL,
                CONTENT_TYPE VARCHAR(120) NOT NULL,
                FILE_PATH CLOB(2M) NOT NULL,
                FILE_SIZE BIGINT,
                CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP
            )';
    END IF;
END@

BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM SYSCAT.INDEXES
        WHERE TABSCHEMA = CURRENT SCHEMA
          AND INDNAME = 'IX_EMAIL_ATTACHMENT_QUEUE'
    ) THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IX_EMAIL_ATTACHMENT_QUEUE ON EMAIL_ATTACHMENT (EMAIL_QUEUE_ID)';
    END IF;
END@
