using System;
using System.Collections.Generic;
using System.Configuration;
using CapaDatos.Models;
using Npgsql;

namespace CapaDatos.DAOs
{
    public sealed class FirmaInstitucionalAocrDAO
    {
        private readonly string _cs;
        public FirmaInstitucionalAocrDAO(){var x=ConfigurationManager.ConnectionStrings["AOCRConnection"];_cs=x!=null?x.ConnectionString:ConexionDAO.CadenaConexion;}
        private NpgsqlConnection Conexion(){return new NpgsqlConnection(_cs);}
        public IList<FirmaInstitucionalAocrFilaDto> ObtenerPendientes(){var list=new List<FirmaInstitucionalAocrFilaDto>();using(var cn=Conexion())using(var cmd=new NpgsqlCommand("SELECT * FROM ("+BaseQueryAll+") q WHERE q.estado_aocr IN ('APROBADO_DCAV','PENDIENTE_FIRMA_DGAC') OR q.estado_condiciones IN ('APROBADO_DCAV','PENDIENTE_FIRMA_DCAV') ORDER BY q.fecha_aprobacion ASC,q.solicitud_id ASC;",cn)){cn.Open();using(var rd=cmd.ExecuteReader())while(rd.Read())list.Add(Map(rd));}return list;}
        public int ContarPendientes(){using(var cn=Conexion())using(var cmd=new NpgsqlCommand("SELECT COUNT(*) FROM ("+BaseQueryAll+") q WHERE q.estado_aocr IN ('APROBADO_DCAV','PENDIENTE_FIRMA_DGAC') OR q.estado_condiciones IN ('APROBADO_DCAV','PENDIENTE_FIRMA_DCAV');",cn)){cn.Open();return Convert.ToInt32(cmd.ExecuteScalar());}}
        public int ContarPendientesDgac(){return ContarPorEstado("estado_aocr",new[]{"APROBADO_DCAV","PENDIENTE_FIRMA_DGAC"});}
        public int ContarPendientesDcav(){return ContarPorEstado("estado_condiciones",new[]{"APROBADO_DCAV","PENDIENTE_FIRMA_DCAV"});}
        private int ContarPorEstado(string columna,string[] estados){using(var cn=Conexion())using(var cmd=new NpgsqlCommand("SELECT COUNT(*) FROM ("+BaseQueryAll+") q WHERE q."+columna+"=ANY(@estados);",cn)){cn.Open();cmd.Parameters.AddWithValue("@estados",estados);return Convert.ToInt32(cmd.ExecuteScalar());}}
        public FirmaInstitucionalAocrDetalleDto ObtenerDetalle(int solicitudId,int inspeccionId)
        {
            using(var cn=Conexion())using(var cmd=new NpgsqlCommand("SELECT * FROM ("+BaseQueryAll+") q WHERE q.solicitud_id=@s AND q.inspeccion_id=@i;",cn))
            {cn.Open();cmd.Parameters.AddWithValue("@s",solicitudId);cmd.Parameters.AddWithValue("@i",inspeccionId);using(var rd=cmd.ExecuteReader()){if(!rd.Read())return null;var x=Map(rd);var d=new FirmaInstitucionalAocrDetalleDto{SolicitudId=x.SolicitudId,InspeccionId=x.InspeccionId,NumeroSolicitud=x.NumeroSolicitud,Explotador=x.Explotador,TipoTramite=x.TipoTramite,Inspector=x.Inspector,UsuarioDcav=x.UsuarioDcav,FechaAprobacion=x.FechaAprobacion,Estado=x.Estado,VersionExpediente=x.VersionExpediente,AocrId=x.AocrId,VersionAocr=x.VersionAocr,AocrPdfId=x.AocrPdfId,EstadoAocr=x.EstadoAocr,CondicionesId=x.CondicionesId,VersionCondiciones=x.VersionCondiciones,CondicionesPdfId=x.CondicionesPdfId,EstadoCondiciones=x.EstadoCondiciones,InformeId=x.InformeId,InformeRuta=x.InformeRuta,LvEaeId=x.LvEaeId,LvEaeRuta=x.LvEaeRuta};rd.Close();d.Historial=Historial(cn,solicitudId,inspeccionId);return d;}}
        }
        private static IList<HistorialDocumentoDcavDto> Historial(NpgsqlConnection cn,int s,int i){var list=new List<HistorialDocumentoDcavDto>();using(var cmd=new NpgsqlCommand(@"SELECT h.id,h.accion,h.usuario_id,TRIM(COALESCE(u.nombreusuario,'')||' '||COALESCE(u.apellidousuario,'')),h.rol_usuario,h.estado_anterior,h.estado_nuevo,h.observacion,h.fecha_creacion,h.correlation_id FROM public.aocr_proceso_estado_historial h LEFT JOIN public.usuario u ON u.idusuario=h.usuario_id WHERE h.solicitud_id=@s AND (h.inspeccion_id=@i OR h.inspeccion_id IS NULL) ORDER BY h.fecha_creacion DESC,h.id DESC;",cn)){cmd.Parameters.AddWithValue("@s",s);cmd.Parameters.AddWithValue("@i",i);using(var rd=cmd.ExecuteReader())while(rd.Read())list.Add(new HistorialDocumentoDcavDto{Id=I(rd,0),Accion=S(rd,1),UsuarioId=rd[2]==DBNull.Value?(int?)null:I(rd,2),UsuarioNombre=S(rd,3),Rol=S(rd,4),EstadoAnterior=S(rd,5),EstadoNuevo=S(rd,6),Observacion=S(rd,7),Fecha=D(rd,8),CorrelationId=S(rd,9)});}return list;}
        private static FirmaInstitucionalAocrFilaDto Map(NpgsqlDataReader r){return new FirmaInstitucionalAocrFilaDto{SolicitudId=I(r,"solicitud_id"),InspeccionId=I(r,"inspeccion_id"),NumeroSolicitud=S(r,"numero_solicitud"),Explotador=S(r,"explotador"),TipoTramite=S(r,"tipo_tramite"),Inspector=S(r,"inspector"),UsuarioDcav=S(r,"usuario_dcav"),FechaAprobacion=D(r,"fecha_aprobacion"),Estado=S(r,"estado"),VersionExpediente=L(r,"version_expediente"),AocrId=I(r,"aocr_id"),VersionAocr=I(r,"version_aocr"),AocrPdfId=I(r,"aocr_pdf_id"),EstadoAocr=S(r,"estado_aocr"),CondicionesId=I(r,"condiciones_id"),VersionCondiciones=I(r,"version_condiciones"),CondicionesPdfId=I(r,"condiciones_pdf_id"),EstadoCondiciones=S(r,"estado_condiciones"),InformeId=I(r,"informe_id"),InformeRuta=S(r,"informe_ruta"),LvEaeId=I(r,"lv_id"),LvEaeRuta=S(r,"lv_ruta")};}
        private static int I(NpgsqlDataReader r,string n){return r[n]==DBNull.Value?0:Convert.ToInt32(r[n]);}private static long L(NpgsqlDataReader r,string n){return r[n]==DBNull.Value?0:Convert.ToInt64(r[n]);}private static int I(NpgsqlDataReader r,int n){return r[n]==DBNull.Value?0:Convert.ToInt32(r[n]);}private static string S(NpgsqlDataReader r,string n){return r[n]==DBNull.Value?null:Convert.ToString(r[n]);}private static string S(NpgsqlDataReader r,int n){return r[n]==DBNull.Value?null:Convert.ToString(r[n]);}private static DateTime D(NpgsqlDataReader r,string n){return r[n]==DBNull.Value?DateTime.MinValue:Convert.ToDateTime(r[n]);}private static DateTime D(NpgsqlDataReader r,int n){return r[n]==DBNull.Value?DateTime.MinValue:Convert.ToDateTime(r[n]);}
        private static string BaseQueryAll
        {
            get
            {
                return BaseQuery.Replace(
                    "pe.estado_actual IN ('PENDIENTE_FIRMA_DIRDAC','PENDIENTE_FIRMAS_INSTITUCIONALES')",
                    "pe.estado_actual IN ('PENDIENTE_FIRMA_DIRDAC','PENDIENTE_FIRMAS_INSTITUCIONALES','DOCUMENTOS_FIRMADOS_INSTITUCIONALMENTE')");
            }
        }
        private const string BaseQuery=@"SELECT s.codigo_solicitud solicitud_id,i.codigo_inspeccion inspeccion_id,s.numero_solicitud,COALESCE(NULLIF(s.razon_social,''),NULLIF(s.nombre_operador,''),s.nombre_comercial,'') explotador,COALESCE(s.tipo_operacion,s.tipo_solicitud::text) tipo_tramite,TRIM(COALESCE(ui.nombreusuario,'')||' '||COALESCE(ui.apellidousuario,'')) inspector,TRIM(COALESCE(ud.nombreusuario,'')||' '||COALESCE(ud.apellidousuario,'')) usuario_dcav,ap.fecha_creacion fecha_aprobacion,pe.estado_actual estado,pe.version version_expediente,a.codigo_documento aocr_id,a.version version_aocr,a.estado estado_aocr,pa.codigo_documento aocr_pdf_id,c.codigo_documento condiciones_id,c.version version_condiciones,c.estado estado_condiciones,pc.codigo_documento condiciones_pdf_id,inf.codigo_informe informe_id,inf.ruta_documento_firmado informe_ruta,lv.codigo_lv lv_id,lv.ruta_documento_firmado lv_ruta FROM public.aocr_proceso_estado pe JOIN public.aocr_tbsolicitud s ON s.codigo_solicitud=pe.solicitud_id AND s.deleted_at IS NULL JOIN public.aocr_tbinspeccion i ON i.codigo_inspeccion=pe.inspeccion_id AND i.codigo_solicitud=s.codigo_solicitud LEFT JOIN public.usuario ui ON ui.idusuario=COALESCE(i.codigo_inspector,s.codigo_tecnico) JOIN LATERAL(SELECT h.* FROM public.aocr_proceso_estado_historial h WHERE h.solicitud_id=s.codigo_solicitud AND h.inspeccion_id=i.codigo_inspeccion AND h.accion='APROBAR_DOCUMENTOS_DCAV' ORDER BY h.fecha_creacion DESC,h.id DESC LIMIT 1) ap ON TRUE LEFT JOIN public.usuario ud ON ud.idusuario=ap.usuario_id JOIN public.aocr_tbdocumento_generado a ON a.codigo_documento=substring(ap.observacion from 'AocrId=([0-9]+)')::integer AND a.codigo_solicitud=s.codigo_solicitud AND a.estado IN ('APROBADO_DCAV','PENDIENTE_FIRMA_DGAC','FIRMADO_DGAC') AND a.vigente=TRUE AND a.eliminado=FALSE JOIN public.aocr_tbdocumento_generado c ON c.codigo_documento=substring(ap.observacion from 'CondicionesId=([0-9]+)')::integer AND c.codigo_solicitud=s.codigo_solicitud AND c.estado IN ('APROBADO_DCAV','PENDIENTE_FIRMA_DCAV','FIRMADO_DCAV') AND c.vigente=TRUE AND c.eliminado=FALSE JOIN public.aocr_tbdocumento_inspeccion pa ON pa.codigo_documento=substring(ap.observacion from 'AocrPdfId=([0-9]+)')::integer AND pa.codigo_documento_base=a.codigo_documento JOIN public.aocr_tbdocumento_inspeccion pc ON pc.codigo_documento=substring(ap.observacion from 'CondicionesPdfId=([0-9]+)')::integer AND pc.codigo_documento_base=c.codigo_documento JOIN public.aocr_tbinforme_inspeccion inf ON inf.codigo_informe=substring(ap.observacion from 'InformeTecnicoId=([0-9]+)')::integer AND inf.codigo_inspeccion=i.codigo_inspeccion JOIN public.aocr_tblv_operacional_eae lv ON lv.codigo_lv=substring(ap.observacion from 'LvEaeId=([0-9]+)')::integer AND lv.codigo_inspeccion=i.codigo_inspeccion WHERE pe.activo=TRUE AND pe.estado_actual IN ('PENDIENTE_FIRMA_DIRDAC','PENDIENTE_FIRMAS_INSTITUCIONALES')";
    }
}
